### ISSUE TITLE
Styles not working

### ISSUE THREAD

**Issue by nodahikaru** [backpackapp-io/react-native-toast#12]
I am trying to add border color
`
toast.error(text, {
    disableShadow: true,
    position: ToastPosition.TOP,
    duration: 5000,
    styles: {
      pressable: {
        borderWidth: 2,
        borderColor: '#f00',
      },
    },
  });
`

But styles is not applied.

**Comment by nickdebaise** [comment]
Thanks for reporting! Fixed in #14
