### ISSUE TITLE
Swiping toast upwards to remove breaks APP

### ISSUE THREAD

**Issue by emmyduruc** [backpackapp-io/react-native-toast#13]
* When swiping the toast upwards breaks my app both dev and prod.
here is the error ( ERROR  ReanimatedError: Cannot read property '__workletHash' of undefined, js engine: reanimated)
* version :     "@backpackapp-io/react-native-toast": "^0.9.0",     "react-native": "^0.71.0",     "react-native-reanimated": "^3.3.0",     "react-native-gesture-handler": "^2.9.0",

**Comment by YuGer26** [comment]
me too

**Comment by dalley8626** [comment]
same here

**Comment by nickdebaise** [comment]
Thank you for this report. Seemed to be an issue with reanimated-3 and non-worklet functions. Fixed in #15
