### ISSUE TITLE
when position is `bottom` extraInsets not working

### ISSUE THREAD

**Issue by elliot-forerunner** [backpackapp-io/react-native-toast#18]
I'm trying to get an extra inset working with a bottom position and that doesn't seem to be implemented:

```
<Toasts extraInsets={{bottom: 32}}/>
```

<img width="1512" alt="Screenshot 2023-10-05 at 10 30 41 AM" src="https://github.com/backpackapp-io/react-native-toast/assets/93220486/4e6bb1c9-ea0d-487b-b867-9ec4e12b1549">

I think this can be solved by passing extraInsets to `<Toast/>` and use it in the `startingY` calculation.

**Comment by kg-currenxie** [comment]
Same issue here

**Comment by nickdebaise** [comment]
Thank you! Fixed in next version
