### ISSUE TITLE
Customizability suggestions

### ISSUE THREAD

**Issue by kg-currenxie** [backpackapp-io/react-native-toast#22]
Awesome library first of all! <3

### 1.

Let us customize these animation values:

```
    opacity.value = withTiming(toast.visible ? 1 : 0, {
      duration: 300,
    });

      offsetY.value = withSpring(val, {
        stiffness: 80,
      });

      position.value = withSpring(val, {
        stiffness: 80,
      });
```

### 2.

Styling seems hard (on tablets)
![image](https://github.com/backpackapp-io/react-native-toast/assets/48229166/be2909a7-6a0f-4e90-937a-0274e93738e0)

I'd like it to be centered, and just based on the content, but the component is hardcoded to a pixel `width`

Expectations:
![image](https://github.com/backpackapp-io/react-native-toast/assets/48229166/3b30d017-286a-4814-aa03-b3b4d33f64fc)

Let me know if this is doable.

i tried
```
        pressable: {
          backgroundColor: 'transparent',
          alignItems: 'center',
          justifyContent: 'center',
        },
```
and also 
```
view: {
  width: 'auto'
}
```

but it doesnt work :P

**Comment by kg-currenxie** [comment]
I managed the styling with a customToast

```
  function showToast(text: string, id?: string): void {
    toast(text, {
      id: id,
      duration: 3000,
      position: ToastPosition.BOTTOM,
      height: 36,
      customToast: (t) => {
        return (
          <View
            style={{
              height: t.height,
              width: t.width,
              justifyContent: 'center',
              alignItems: 'center',
            }}
          >
            <View
              style={{
                backgroundColor: '#088',
                borderRadius: 100,
              }}
            >
              {typeof t.message !== 'function' && (
                <Text
                  style={{
                    color: '#ffffff',
                    fontSize: 14,
                    fontWeight: '500',
                    textAlign: 'center',
                    paddingVertical: 9,
                    paddingHorizontal: 16,
                  }}
                >
                  {t.message}
                </Text>
              )}
            </View>
          </View>
        )
      },
    })
  }
```

FYI `typeof t.message !== 'function'` is a hack to prevent TS error.`message: ValueOrFunction<Element, Toast>` doesn't play well with <Text>

**Comment by thoth-seshat** [comment]
I'm doing a custom toast the same way for global styling, it's an "ok" solution but I'm not sure it works great with promise toasts. 

I'd also like to be able to customize animations. Hoping this library still gets maintained, maybe just fork it for now

**Comment by nickdebaise** [comment]
Thanks for the suggestions! I have added an animationConfig toast property and constrained the maxWidth of the toast to 360 if it exceeds that width (e.g., on tablet devices). To achieve auto width with centered text, apply the following styles:

```
styles: {
  pressable: {
    maxWidth: width - 32,
    alignSelf: 'center',
    left: null,
    paddingHorizontal: 16,
  },
  view: {
    flexGrow: 1,
    flexShrink: 1,
    maxWidth: width - 32,
    paddingHorizontal: 0,
    width: undefined,
  },
  text: {
    flex: undefined,
    flexGrow: 1,
    flexShrink: 1,
    flexWrap: 'wrap',
  },
}
```

These styles can be applied to the defaultStyle prop in the <Toasts /> component or to each toast instance individually. If you use these styles frequently, I recommend creating an object that you can add directly to each toast call, e.g.,

```
toast('my toast', {
  styles: AutoWidthStyles
});
```

where AutoWidthStyles holds the actual styles for auto width.

Thanks!
