### ISSUE TITLE
Ghost Toast?

### ISSUE THREAD

**Issue by kyle-belle** [backpackapp-io/react-native-toast#23]
There seems to be some invisible/ghost toast near the top of my app's screen which stops me from being able to press any button is the region
![Screenshot_20240121-142538](https://github.com/backpackapp-io/react-native-toast/assets/43228761/5350f3be-b408-4c08-aa02-e42341965ef2)

any idea why this happens?

**Comment by marcin-spotio** [comment]
@kyle-belle I noticed that as well. After a toast is dismissed, it stays on the screen for half a second while being invisible (0 opacity). It still reacts to taps. Here's my patch to push it off the screen (I use npx patch-package):

`diff --git a/node_modules/@backpackapp-io/react-native-toast/src/components/Toast.tsx b/node_modules/@backpackapp-io/react-native-toast/src/components/Toast.tsx
index a16cb43..9e1f067 100644
--- a/node_modules/@backpackapp-io/react-native-toast/src/components/Toast.tsx
+++ b/node_modules/@backpackapp-io/react-native-toast/src/components/Toast.tsx
@@ -86,9 +86,9 @@ export const Toast: FC<Props> = ({
   const startingY = useMemo(
     () =>
       toast.position === ToastPosition.TOP
-        ? -50
+        ?  - (toast.height || DEFAULT_TOAST_HEIGHT) - insets.top - 50
         : height - insets.bottom - Platform.select({ ios: 0, default: 32 }),
-    [height, toast.position, insets.bottom]
+    [height, toast.position, insets.bottom, insets.top, toast.height]
   );
 
   const opacity = useSharedValue(0);
`

**Comment by marcin-spotio** [comment]
@kyle-belle I noticed that as well. After a toast is dismissed, it stays on the screen for half a second while being invisible (0 opacity). It still reacts to taps. Here's my patch to push it off the screen (I use npx patch-package):

[@backpackapp-io+react-native-toast+0.10.0.patch](https://github.com/backpackapp-io/react-native-toast/files/15358879/%40backpackapp-io%2Breact-native-toast%2B0.10.0.patch)

**Comment by nickdebaise** [comment]
Thanks! @marcin-spotio should be fixed in next version
