### ISSUE TITLE
findNodeHandle is deprecated in StrictMode

### ISSUE THREAD

**Issue by Framsynt** [backpackapp-io/react-native-toast#27]
I am getting `findNodeHandle is deprecated in StrictMode` warning. It is coming from `AnimatedComponent` in `react-native-reanimated`. 

Afaik, it can be solved by adding nodeRef to `AnimatedPressable`.

**Comment by nickdebaise** [comment]
Can you provide a reproducible example? I'm not seeing this in strict mode.
