### ISSUE TITLE
Error: No safe area value available. Make sure you are rendering `<SafeAreaProvider>` at the top of your app.

### ISSUE THREAD

**Issue by thoth-seshat** [backpackapp-io/react-native-toast#28]
I'm using `"react-native-safe-area-context": "^4.2.4"`

I'm getting this error when trying to use the <Toast /> component in my App.tsx file

**Comment by thoth-seshat** [comment]
I was able to fix this by wrapping <SafeAreaProvider> around my app. I don't think this is documented

**Comment by nickdebaise** [comment]
Documented now, thank you!
