### ISSUE TITLE
When using a `customToast` my toast appears slightly off the right side of the screen

### ISSUE THREAD

**Issue by salieflewis** [backpackapp-io/react-native-toast#37]
<img width="699" alt="Screenshot 2024-09-02 at 12 43 44 PM" src="https://github.com/user-attachments/assets/30d6eec2-30ea-4640-915e-dfb58030c092">

Not sure why this is happening. Does not happen when not using a custom toast.

**Comment by bill9222729** [comment]
You need to feed the width from customToast into the toast parameters.
Otherwise, it will use the default value for calculation, causing an offset.

<img width="808" alt="image" src="https://github.com/user-attachments/assets/f448da75-8721-496c-a70f-d8691281c6af">

**Comment by salieflewis** [comment]
> You need to feed the width from customToast into the toast parameters. Otherwise, it will use the default value for calculation, causing an offset.
> 
> <img alt="image" width="808" src="https://private-user-images.githubusercontent.com/32421831/372384430-f448da75-8721-496c-a70f-d8691281c6af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MDAzNjUsIm5iZiI6MTcyNzgwMDA2NSwicGF0aCI6Ii8zMjQyMTgzMS8zNzIzODQ0MzAtZjQ0OGRhNzUtODcyMS00OTZjLWE3MGYtZDg2OTEyODFjNmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE2Mjc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMjJjZGU4OGUwMDg2Yjk1OTEwZWU4ZTUxNWU2ZGQ1YTgwM2RkMjdiNzY5NTcyNWEzZjhkNTAwNmM3NGEwZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c2oXID3ZG2uBYXbKUSHNJcwZqKPxi21FFWx6NfXslb4">

I was able to figure this out. But my implementation is very verbose because of this. Ex:

```
customToast: (toast) => (
        <CustomToast isLoading={true} dimensions={dimensions} toast={toast} />
      ),
      width: dimensions.width - 32,
      position: ToastPosition.BOTTOM,
 ```
 
 Where `CustomToast` also has a custom width property `width={dimensions.width - 32}`
