### ISSUE TITLE
Request for documentation surrounding `animationConfig`

### ISSUE THREAD

**Issue by salieflewis** [backpackapp-io/react-native-toast#38]
Personally not a fan of the bouncy animation and I'm curious about how I can adjust this prop to remove it.

**Comment by fredrifoUni** [comment]
@salieflewis 

I created a quick patch that reduces the bounce effect - https://github.com/backpackapp-io/react-native-toast/issues/35#issuecomment-2372734871

**Comment by salieflewis** [comment]
Thank you @fredrifoUni 

I tried recreating this patch but nothing changed for me. Are there further adjustments I need to make when actually calling the toast for these styles to apply?

**Comment by fredrifoUni** [comment]
> Thank you @fredrifoUni
> 
> I tried recreating this patch but nothing changed for me. Are there further adjustments I need to make when actually calling the toast for these styles to apply?

No problem! This patch only works when passing `position: ToastPosition.BOTTOM` in the `ToastOptions`. If you want to modify it for `ToastPosition.TOP`, you'll have to patch the other if statement.

**Comment by nickdebaise** [comment]
Will be fixed once #40 is merged allowing for total control over animationConfig
