### ISSUE TITLE
V0.12.0 throws error with EXPO SDK 52

### ISSUE THREAD

**Issue by jingp-ofload** [backpackapp-io/react-native-toast#43]
Unable to resolve "src/core/utils" from "node_modules/@backpackapp-io/react-native-toast/src/components/Toasts.tsx"

**Comment by ArviinM** [comment]
I need this fix ASAP

**Comment by nickdebaise** [comment]
Fixed for expo sdk 52. Tested by creating new expo sdk 52 project, installing dependencies, and testing library. Please reopen if any issues.
