### ISSUE TITLE
globalAnimationType="spring" not working

### ISSUE THREAD

**Issue by troyeguo** [backpackapp-io/react-native-toast#46]
When i set globalAnimationType="spring", the toast still followed the timing animation. Here is my code.

```
<Toasts
    globalAnimationType="spring"
    globalAnimationConfig={{
      duration: 500,
      stiffness: 120,
    }}
  />

toast("Hello");
```

Only animationType: "spring" works when passing as config in toast function

```
toast("Hello", {
  animationType: "spring",
});
```

**Comment by nickdebaise** [comment]
I have pushed a fix recently to Github and it will be in the next release (in the coming days). If you need this fix asap, you can install the GitHub repo as the npm package.

The issue lied in the fact that we were assigning a "timing" config to each toast if it did not have an animationType, which overrode the global animation type.

[Commit](https://github.com/backpackapp-io/react-native-toast/commit/08c2708b61bb3be0e131a8e77f868bf1faa7f7b7#diff-753d47d5a4a5b2a6b46382e912325dac57a6e736ebc1382b1b85242197f53f0dR71)
