### ISSUE TITLE
Remove the default shadow when using a custom toast component

### ISSUE THREAD

**Issue by salieflewis** [backpackapp-io/react-native-toast#50]
![simulator_screenshot_DDD93F6A-E0A7-4E94-A110-4239E21E7654](https://github.com/user-attachments/assets/f19c3dba-3098-4251-8a33-2064d4efadc8)

**Comment by nickdebaise** [comment]
You can disable the shadow by passing a disableShadow prop when creating the toast:

https://docs.backpackapp.io/react-native-toast/api/toast/#disable-shadow

If that doesn’t work, you can override the default pressable style by ensuring that shadow properties are undefined. See: https://docs.backpackapp.io/react-native-toast/features/customization#styling-customization
